# IN PROGRESS!!!!
version: "3"

services:
  db:
    container_name: teachers-trade-psql
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    volumes:
      - ./docker/postgres:/var/lib/postgresql/data
    # ports:
    #   - "6961:5432"  #! Testing only!
    networks:
      - teachers-trade-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: teachers-trade-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "23439:80"
    volumes:
      - ./docker/pgadmin:/var/lib/pgadmin
    networks:
      - teachers-trade-network
    depends_on:
      - db

networks:
  teachers-trade-network:
    name: teachers-trade-network